### PR TITLE
Adjust required parameters for .identify()

### PR DESCRIPTION
**Pull request by c990802**
As the official customerio REST API states, only `id` is a required field (http://customer.io/docs/api/rest.html#section-Creating_or_updating_customers). The reason being that if an update is performed, it shouldn't be required to send *email* and *created_at* again.

### CODE REVIEW

**Comment by c990802** [comment]
@chrisjhoughton what are your thoughts on this PR?

**Comment by chrisjhoughton** [comment]
Hi @c990802 thanks for contributing here! I agree - there's no point in us requiring parameters when CIO doesn't require them themselves.

I've just had a read of the docs you linked to, it seems the email is also required: 

> email (required) – the email address of the user.

I'll take a look over the `created_at` tonight.

**Comment by c990802** [comment]
great. Many thanks.

**Comment by chrisjhoughton** [comment]
Interesting - I've just run some tests and it looks like it's possible to identify users __without__ both of the `created_at` and `email` keys.

However, I'm hesitant to remove them, considering there are places in the docs that say that both `email` and `created_at` are required:

screen shot 2015-05-19 at 22 20 37

What's your main need/use-case to remove these?

**Comment by c990802** [comment]
Yes, it's true, users can be created without *email* and/or *created_at*.

The main issue here is that cio API uses an update operation for both create & update users. As stated [here](http://customer.io/docs/api/rest.html#section-Arguments) the `identify`method is in essence a PUT operation.

My use case is precisely on updating operations done in our system that eventually must be synced with cio. For example, email address updates, or passing new/updated parameters to cio to make use of their segmentation feature. For none of these operations, `created_at` should be a required field. Similarly, `email` shouldn't be required either if the purpose is to update other attributes.

I see two options here: Try to be as aligned as possible with cio or choose an opinionated approach. The former would require to remove the requirements. If you choose the latter, I think the most expressive solution is to maintain `identify` as is, and create an `update` method with the exact same functionality, but not requiring `email` and `created_at`.

btw, I am more in favour of an opinionated approach.

lmk your thoughts, and thanks for the help!

**Comment by chrisjhoughton** [comment]
Hey! Sorry for taking such a long time to get back to you on this, been crazy busy on my end.

You're spot on with those two different options, although I think we disagree slightly here - my view is that this module should be as close as possible to the CIO approach to ensure maximum reliability. It also means that people can very easily come from the client-side JS model and instantly dive in here, rather than have to learn about an extra method.

By all means fork the module to do otherwise! I think we both agree it's a relatively minor change here.

**Pull request closed without merging**
